In [ ]:
import pandas as pd

In [ ]:
import numpy as np

In [ ]:
print("Librerías cargadas correctamente")

Librerías cargadas correctamente

In [4]:
import os

In [5]:
print(os.getcwd())

c:\Users\Jose Departamento TI\OneDrive - districom de colombia S.A.S\Escritorio\personal\CIAF\10 SEMESTRE\Mineria de Datos\Turismov1\notebooks

In [6]:
rnt = pd.read_excel("../data/thwd-ivmp.xlsx")

FileNotFoundError: [Errno 2] No such file or directory: '../data/thwd-ivmp.xlsx'

In [7]:
import os

In [8]:
print(os.getcwd())

c:\Users\Jose Departamento TI\OneDrive - districom de colombia S.A.S\Escritorio\personal\CIAF\10 SEMESTRE\Mineria de Datos\Turismov1\notebooks

In [9]:
import os

In [10]:
print(os.listdir("."))

['Notebook_Adquisicion_FINAL.ipynb']

In [11]:
print(os.listdir(".."))

['data', 'notebooks']

In [12]:
import os

print(os.listdir("../data"))

['anex-EMA-jul2026 (1).xlsx', 'thwd-ivmp.xlsx']

In [13]:
rnt = pd.read_excel("../data/thwd-ivmp.xlsx")

print(rnt.shape)

(1000, 1)

In [14]:
rnt = rnt.iloc[:,0].str.split(",", expand=True)

print(rnt.shape)

rnt.head()

(1000, 14)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,11,"""ACTIVO""","""BCD TRAVEL OFICINA PRINCIPAL""","""BOGOTA""","""11""","""BOGOTA D.C.""","""11001""","""800078692""","""AGENCIAS DE VIAJES""","""AGENCIA DE VIAJES Y DE TURISMO""","""0""","""0""","""110""","""2026"""
1,61,"""ACTIVO""","""AVIATUR CARTAGENA""","""BOLIVAR""","""13""","""CARTAGENA""","""13001""","""860000018""","""AGENCIAS DE VIAJES""","""AGENCIA DE VIAJES Y DE TURISMO""","""0""","""0""","""16""","""2026"""
2,68,"""ACTIVO""","""AVIATUR CALI LA FLORA""","""VALLE DEL CAUCA""","""76""","""CALI""","""76001""","""860000018""","""AGENCIAS DE VIAJES""","""AGENCIA DE VIAJES Y DE TURISMO""","""0""","""0""","""58""","""2026"""
3,79,"""ACTIVO""","""AVIATUR BARRANQUILLA""","""ATLANTICO""","""8""","""BARRANQUILLA""","""08001""","""860000018""","""AGENCIAS DE VIAJES""","""AGENCIA DE VIAJES Y DE TURISMO""","""0""","""0""","""15""","""2026"""
4,86,"""ACTIVO""","""AVIATUR MEDELLIN""","""ANTIOQUIA""","""5""","""MEDELLIN""","""05001""","""860000018""","""AGENCIAS DE VIAJES""","""AGENCIA DE VIAJES Y DE TURISMO""","""0""","""0""","""102""","""2026"""

In [15]:
rnt.columns = [
    "codigo_rnt",
    "estado_rnt",
    "razon_social_establecimiento",
    "departamento",
    "cod_dpto",
    "municipio",
    "cod_mun",
    "nit",
    "categoria",
    "sub_categoria",
    "habitaciones",
    "camas",
    "num_emp1",
    "ano"
]

In [16]:
print(rnt.columns)

Index(['codigo_rnt', 'estado_rnt', 'razon_social_establecimiento',
       'departamento', 'cod_dpto', 'municipio', 'cod_mun', 'nit', 'categoria',
       'sub_categoria', 'habitaciones', 'camas', 'num_emp1', 'ano'],
      dtype='str')

In [17]:
ema = pd.read_excel(
    "../data/anex-EMA-jul2026 (1).xlsx",
    sheet_name=None
)

print("Hojas encontradas:", len(ema))

Hojas encontradas: 25

In [18]:
list(ema.keys())

['Índice',
 '1.1 V.A Ing.real',
 '1.2 V.A.C Ing.real',
 '1.3 V.12Meses Ing.real',
 '2.1 V.A Per.categ',
 '2.2 V.A.C Per.categ',
 '2.3 V.12Meses Per.categ',
 '3.1 V.A Salarios',
 '3.2 V.A.C Salarios',
 '3.3 V.12Meses Salarios',
 '4.1 Porc Ocupación.escala.hab',
 '4.2 Porc Mens Ocupación.reg',
 '4.3 Porc A.C Ocupación.reg',
 '4.4 Porc 12.meses Ocupación.reg',
 '5.1 Porc Mens Motivo.viaje.reg',
 '5.2 Porc AC Motivo.viaje.reg',
 '5.3 Porc Mens Motivo.viaje.R',
 '5.4 Porc Mens Motivo.viaje.NR',
 '5.5 Porc Huéspedes.EMA',
 '6.1 Ind.Var Tarifas.acomoda',
 '7.1 Ind.Mes oferta.demanda',
 '8.1 Ind.EMA',
 '8.2 Ind empalmados.MMH',
 '9.1 Coef.Varia.Naci',
 '9.2 Coef.Variación.Regi']

In [19]:
ocupacion = ema["4.2 Porc Mens Ocupación.reg"]

ocupacion.head(20)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,32
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ENCUESTA MENSUAL DE ALOJAMIENTO - EMA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,4.2 Porcentaje de ocupación mensual,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Total nacional y 12 regiones,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Enero 2019 - julio 2026ᵖ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Año,Meses,Total nacional,Bogotá D.C.,Cartagena,Central,Caribe,Eje Cafetero,Antioquia,San Andrés y Providencia,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,2019,Enero,47.166178,44.804505,67.437514,38.745271,51.009846,49.560509,46.537566,72.012276,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,Febrero,48.248052,58.725596,65.323641,31.369122,45.726525,39.068687,45.38783,71.20798,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,Marzo,47.490489,55.613889,65.873969,31.166316,49.468632,39.481411,44.43692,70.368067,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,Abril,45.743693,53.262452,56.891085,32.934823,44.551978,40.564177,43.427767,71.010904,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,Mayo,45.587579,58.275363,51.67878,28.387679,41.651362,39.478227,44.480696,72.393931,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,Junio,48.343867,57.03571,52.007796,39.791725,46.824913,44.290256,48.244223,72.588305,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,Julio,49.4945,59.187644,58.624365,37.207913,48.488852,43.731396,49.56712,73.413428,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,Agosto,51.788364,59.711529,63.79831,37.777792,51.826227,47.678343,52.772436,76.499468,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,Septiembre,50.068854,61.857672,57.013854,34.774218,48.199832,44.79119,48.351387,76.063008,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
ocupacion_limpia = ocupacion.copy()

ocupacion_limpia.columns = ocupacion_limpia.iloc[10]

ocupacion_limpia = ocupacion_limpia.iloc[11:]

In [21]:
ocupacion_limpia.columns = (
    ocupacion_limpia.columns
    .astype(str)
    .str.strip()
)

In [22]:
print(ocupacion_limpia.columns.tolist())

['Año', 'Meses', 'Total nacional', 'Bogotá D.C.', 'Cartagena', 'Central', 'Caribe', 'Eje Cafetero', 'Antioquia', 'San Andrés y Providencia', 'Pacífico', 'Santanderes', 'Llanos Orinoquía', 'Golfo Morrosquillo y Sabana', 'Amazonía', nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]

In [23]:
print(ocupacion_limpia.columns.tolist())

['Año', 'Meses', 'Total nacional', 'Bogotá D.C.', 'Cartagena', 'Central', 'Caribe', 'Eje Cafetero', 'Antioquia', 'San Andrés y Providencia', 'Pacífico', 'Santanderes', 'Llanos Orinoquía', 'Golfo Morrosquillo y Sabana', 'Amazonía', nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]

In [24]:
Pacífico
Santanderes
Llanos Orinoquía
Amazonía

SyntaxError: invalid syntax (2844853593.py, line 3)

In [25]:
ocupacion_limpia = ocupacion_limpia.loc[
    :,
ocupacion_limpia.columns.notna()
]

In [26]:
print(len(ocupacion_limpia.columns))

15

In [27]:
columnas_regiones = list(
    ocupacion_limpia.columns[2:14]
)

print(columnas_regiones)

['Total nacional', 'Bogotá D.C.', 'Cartagena', 'Central', 'Caribe', 'Eje Cafetero', 'Antioquia', 'San Andrés y Providencia', 'Pacífico', 'Santanderes', 'Llanos Orinoquía', 'Golfo Morrosquillo y Sabana']

In [28]:
ocupacion_long = pd.melt(
    ocupacion_limpia,
    id_vars=["Año", "Meses"],
    value_vars=columnas_regiones,
    var_name="region",
    value_name="ocupacion"
)

In [29]:
for col in ocupacion_limpia.columns:
    print(repr(col))

'Año'
'Meses'
'Total nacional'
'Bogotá D.C.'
'Cartagena'
'Central'
'Caribe'
'Eje Cafetero'
'Antioquia'
'San Andrés y Providencia'
'Pacífico'
'Santanderes'
'Llanos Orinoquía'
'Golfo Morrosquillo y Sabana'
'Amazonía'

In [30]:
columnas_regiones = list(ocupacion_limpia.columns[2:14])

print(columnas_regiones)

['Total nacional', 'Bogotá D.C.', 'Cartagena', 'Central', 'Caribe', 'Eje Cafetero', 'Antioquia', 'San Andrés y Providencia', 'Pacífico', 'Santanderes', 'Llanos Orinoquía', 'Golfo Morrosquillo y Sabana']

In [31]:
columnas_regiones = list(
    ocupacion_limpia.columns[3:15]
)

print(columnas_regiones)

['Bogotá D.C.', 'Cartagena', 'Central', 'Caribe', 'Eje Cafetero', 'Antioquia', 'San Andrés y Providencia', 'Pacífico', 'Santanderes', 'Llanos Orinoquía', 'Golfo Morrosquillo y Sabana', 'Amazonía']

In [32]:
ocupacion_long = pd.melt(
    ocupacion_limpia,
    id_vars=["Año", "Meses"],
    value_vars=columnas_regiones,
    var_name="region",
    value_name="ocupacion"
)

In [33]:
print(ocupacion_long.shape)

ocupacion_long.head()

(1188, 4)

    Año    Meses       region  ocupacion
0  2019    Enero  Bogotá D.C.  44.804505
1   NaN  Febrero  Bogotá D.C.  58.725596
2   NaN    Marzo  Bogotá D.C.  55.613889
3   NaN    Abril  Bogotá D.C.  53.262452
4   NaN     Mayo  Bogotá D.C.  58.275363

In [34]:
ocupacion_long["Año"].unique()

array([2019, nan, 2020, 2021, 2022, '2023p', '2024p', '2025p', '2026p'],
      dtype=object)

In [35]:
ocupacion_limpia[["Año","Meses"]].head(20)

10   Año       Meses
11  2019       Enero
12   NaN     Febrero
13   NaN       Marzo
14   NaN       Abril
15   NaN        Mayo
16   NaN       Junio
17   NaN       Julio
18   NaN      Agosto
19   NaN  Septiembre
20   NaN     Octubre
21   NaN   Noviembre
22   NaN   Diciembre
23  2020       Enero
24   NaN     Febrero
25   NaN       Marzo
26   NaN       Abril
27   NaN        Mayo
28   NaN       Junio
29   NaN       Julio
30   NaN      Agosto

In [36]:
ocupacion_limpia["Año"] = (
    ocupacion_limpia["Año"]
    .ffill()
)

In [37]:
ocupacion_limpia[["Año","Meses"]].head(15)

10   Año       Meses
11  2019       Enero
12  2019     Febrero
13  2019       Marzo
14  2019       Abril
15  2019        Mayo
16  2019       Junio
17  2019       Julio
18  2019      Agosto
19  2019  Septiembre
20  2019     Octubre
21  2019   Noviembre
22  2019   Diciembre
23  2020       Enero
24  2020     Febrero
25  2020       Marzo

In [38]:
ocupacion_limpia["Año"] = (
    ocupacion_limpia["Año"]
    .astype(str)
    .str.replace("p", "", regex=False)
)

In [39]:
ocupacion_limpia["Año"] = pd.to_numeric(
    ocupacion_limpia["Año"],
    errors="coerce"
)

In [40]:
sorted(
    ocupacion_limpia["Año"]
    .dropna()
    .unique()
)

[np.int64(2019),
 np.int64(2020),
 np.int64(2021),
 np.int64(2022),
 np.int64(2023),
 np.int64(2024),
 np.int64(2025),
 np.int64(2026)]

In [41]:
ocupacion_long = pd.melt(
    ocupacion_limpia,
    id_vars=["Año", "Meses"],
    value_vars=columnas_regiones,
    var_name="region",
    value_name="ocupacion"
)

In [42]:
print(ocupacion_long.shape)

ocupacion_long.head()

(1188, 4)

    Año    Meses       region  ocupacion
0  2019    Enero  Bogotá D.C.  44.804505
1  2019  Febrero  Bogotá D.C.  58.725596
2  2019    Marzo  Bogotá D.C.  55.613889
3  2019    Abril  Bogotá D.C.  53.262452
4  2019     Mayo  Bogotá D.C.  58.275363

In [43]:
sorted(
    ocupacion_long["Año"]
    .dropna()
    .unique()
)

[np.int64(2019),
 np.int64(2020),
 np.int64(2021),
 np.int64(2022),
 np.int64(2023),
 np.int64(2024),
 np.int64(2025),
 np.int64(2026)]

In [44]:
rnt_hoteles = rnt[
    rnt["categoria"]
    .str.contains("ALOJAMIENTO", case=False, na=False)
]

print(rnt_hoteles.shape)

(498, 14)

In [45]:
for col in rnt_hoteles.columns:
    rnt_hoteles[col] = (
        rnt_hoteles[col]
        .astype(str)
        .str.replace('"', '', regex=False)
        .str.strip()
)

In [46]:
rnt_hoteles.head()

,codigo_rnt,estado_rnt,razon_social_establecimiento,departamento,cod_dpto,municipio,cod_mun,nit,categoria,sub_categoria,habitaciones,camas,num_emp1,ano
7,123,ACTIVO,HOTEL PUERTA DEL SOL S.A.,ATLANTICO,8,BARRANQUILLA,08001,800157788,ESTABLECIMIENTOS DE ALOJAMIENTO TURÃSTICO,HOTEL,109,170,36,2026
12,181,ACTIVO,HOTEL SORATAMA,RISARALDA,66,PEREIRA,66001,800156522,ESTABLECIMIENTOS DE ALOJAMIENTO TURÃSTICO,HOTEL,77,92,51,2026
13,185,ACTIVO,ERTUR LTDA. Y/O HOTEL VERDE MAR,SAN ANDRES Y PROVIDENCIA,88,SAN ANDRES,88001,860508374,ESTABLECIMIENTOS DE ALOJAMIENTO TURÃSTICO,HOTEL,44,166,32,2026
16,253,ACTIVO,HOTEL CASINO INTERNACIONAL,NORTE DE SANTANDER,54,CUCUTA,54001,890502101,ESTABLECIMIENTOS DE ALOJAMIENTO TURÃSTICO,HOTEL,128,173,64,2026
17,254,ACTIVO,HOTEL IROTAMA,MAGDALENA,47,SANTA MARTA,47001,891700612,ESTABLECIMIENTOS DE ALOJAMIENTO TURÃSTICO,HOTEL,192,300,560,2026

In [47]:
sorted(
    ocupacion_long["Año"]
    .dropna()
    .unique()
)

[np.int64(2019),
 np.int64(2020),
 np.int64(2021),
 np.int64(2022),
 np.int64(2023),
 np.int64(2024),
 np.int64(2025),
 np.int64(2026)]

In [48]:
rnt_hoteles = rnt[
    rnt["categoria"]
    .str.contains(
        "ALOJAMIENTO",
        case=False,
        na=False
    )
]

print(rnt_hoteles.shape)

(498, 14)

In [49]:
for col in rnt_hoteles.columns:

rnt_hoteles[col] = (
    rnt_hoteles[col]
        .astype(str)
        .str.replace('"', '', regex=False)
        .str.strip()
    )

rnt_hoteles.head()

IndentationError: expected an indented block after 'for' statement on line 1 (940270562.py, line 3)

In [50]:
for col in rnt_hoteles.columns:

    rnt_hoteles[col] = (
        rnt_hoteles[col]
        .astype(str)
        .str.replace('"', '', regex=False)
        .str.strip()
    )

rnt_hoteles.head()

,codigo_rnt,estado_rnt,razon_social_establecimiento,departamento,cod_dpto,municipio,cod_mun,nit,categoria,sub_categoria,habitaciones,camas,num_emp1,ano
7,123,ACTIVO,HOTEL PUERTA DEL SOL S.A.,ATLANTICO,8,BARRANQUILLA,08001,800157788,ESTABLECIMIENTOS DE ALOJAMIENTO TURÃSTICO,HOTEL,109,170,36,2026
12,181,ACTIVO,HOTEL SORATAMA,RISARALDA,66,PEREIRA,66001,800156522,ESTABLECIMIENTOS DE ALOJAMIENTO TURÃSTICO,HOTEL,77,92,51,2026
13,185,ACTIVO,ERTUR LTDA. Y/O HOTEL VERDE MAR,SAN ANDRES Y PROVIDENCIA,88,SAN ANDRES,88001,860508374,ESTABLECIMIENTOS DE ALOJAMIENTO TURÃSTICO,HOTEL,44,166,32,2026
16,253,ACTIVO,HOTEL CASINO INTERNACIONAL,NORTE DE SANTANDER,54,CUCUTA,54001,890502101,ESTABLECIMIENTOS DE ALOJAMIENTO TURÃSTICO,HOTEL,128,173,64,2026
17,254,ACTIVO,HOTEL IROTAMA,MAGDALENA,47,SANTA MARTA,47001,891700612,ESTABLECIMIENTOS DE ALOJAMIENTO TURÃSTICO,HOTEL,192,300,560,2026

In [57]:
mapa_region = {

"ANTIOQUIA": "Antioquia",

"ATLANTICO": "Caribe",
"CESAR": "Caribe",
"MAGDALENA": "Caribe",
"LA GUAJIRA": "Caribe",

"CALDAS": "Eje Cafetero",
"QUINDIO": "Eje Cafetero",
"RISARALDA": "Eje Cafetero",

"VALLE DEL CAUCA": "Pacífico",
"CAUCA": "Pacífico",
"NARIÑO": "Pacífico",
"CHOCO": "Pacífico",

"SANTANDER": "Santanderes",
"NORTE DE SANTANDER": "Santanderes",

"META": "Llanos Orinoquía",
"ARAUCA": "Llanos Orinoquía",
"CASANARE": "Llanos Orinoquía",
"VICHADA": "Llanos Orinoquía",

"AMAZONAS": "Amazonía",
"CAQUETA": "Amazonía",
"PUTUMAYO": "Amazonía",
"GUAINIA": "Amazonía",
"GUAVIARE": "Amazonía",
"VAUPES": "Amazonía",

"BOGOTA": "Bogotá D.C.",

"CUNDINAMARCA": "Central",
"BOYACA": "Central",
"HUILA": "Central",
"TOLIMA": "Central",

"CORDOBA": "Golfo Morrosquillo y Sabana",
"SUCRE": "Golfo Morrosquillo y Sabana",

"SAN ANDRES Y PROVIDENCIA": "San Andrés y Providencia",

"BOLIVAR": "Cartagena"

}

In [52]:
rnt_hoteles["region"] = (
    rnt_hoteles["departamento"]
    .str.upper()
    .map(mapa_region)
)

rnt_hoteles[
    ["departamento","region"]
].head(20)

                departamento        region
7                  ATLANTICO        Caribe
12                 RISARALDA  Eje Cafetero
13  SAN ANDRES Y PROVIDENCIA           NaN
16        NORTE DE SANTANDER   Santanderes
17                 MAGDALENA        Caribe
19                   BOLIVAR     Cartagena
25                 MAGDALENA        Caribe
30                 RISARALDA  Eje Cafetero
34                    BOGOTA           NaN
35  SAN ANDRES Y PROVIDENCIA           NaN
40                    BOGOTA           NaN
42        NORTE DE SANTANDER   Santanderes
50           VALLE DEL CAUCA      Pacífico
51           VALLE DEL CAUCA      Pacífico
62                    BOGOTA           NaN
64                   BOLIVAR     Cartagena
67                   QUINDIO  Eje Cafetero
84                   NARIÃ‘O           NaN
85                   NARIÃ‘O           NaN
87           VALLE DEL CAUCA      Pacífico

In [53]:
rnt_resumen = (
    rnt_hoteles
    .groupby("region", as_index=False)
    .agg(
        establecimientos=("codigo_rnt","count"),
        habitaciones=("habitaciones","count")
    )
)

rnt_resumen

             region  establecimientos  habitaciones
0          Amazonía                 7             7
1         Antioquia                32            32
2            Caribe                38            38
3         Cartagena                16            16
4      Eje Cafetero                38            38
5  Llanos Orinoquía                16            16
6          Pacífico                49            49
7       Santanderes                49            49

In [54]:
rnt_resumen

             region  establecimientos  habitaciones
0          Amazonía                 7             7
1         Antioquia                32            32
2            Caribe                38            38
3         Cartagena                16            16
4      Eje Cafetero                38            38
5  Llanos Orinoquía                16            16
6          Pacífico                49            49
7       Santanderes                49            49

In [55]:
print("Regiones EMA")
print(sorted(ocupacion_long["region"].unique()))

print("\nRegiones RNT")
print(sorted(rnt_resumen["region"].unique()))

Regiones EMA
['Amazonía', 'Antioquia', 'Bogotá D.C.', 'Caribe', 'Cartagena', 'Central', 'Eje Cafetero', 'Golfo Morrosquillo y Sabana', 'Llanos Orinoquía', 'Pacífico', 'San Andrés y Providencia', 'Santanderes']

Regiones RNT
['Amazonía', 'Antioquia', 'Caribe', 'Cartagena', 'Eje Cafetero', 'Llanos Orinoquía', 'Pacífico', 'Santanderes']

In [56]:
# Bogotá
"BOGOTA": "Bogotá D.C.",

# Región Central
"CUNDINAMARCA": "Central",
"BOYACA": "Central",
"HUILA": "Central",
"TOLIMA": "Central",

# Golfo Morrosquillo y Sabana
"CORDOBA": "Golfo Morrosquillo y Sabana",
"SUCRE": "Golfo Morrosquillo y Sabana",

# San Andrés
"SAN ANDRES Y PROVIDENCIA": "San Andrés y Providencia"

SyntaxError: illegal target for annotation (3677478467.py, line 2)

In [58]:
rnt_hoteles["region"] = (
    rnt_hoteles["departamento"]
    .str.upper()
    .map(mapa_region)
)

In [59]:
rnt_resumen = (
    rnt_hoteles
    .groupby("region", as_index=False)
    .agg(
        establecimientos=("codigo_rnt","count"),
        habitaciones=("habitaciones","count")
    )
)

In [60]:
print(sorted(rnt_resumen["region"].unique()))

['Amazonía', 'Antioquia', 'Bogotá D.C.', 'Caribe', 'Cartagena', 'Central', 'Eje Cafetero', 'Golfo Morrosquillo y Sabana', 'Llanos Orinoquía', 'Pacífico', 'San Andrés y Providencia', 'Santanderes']

In [61]:
print(sorted(ocupacion_long["region"].unique()))

print("\n")

print(sorted(rnt_resumen["region"].unique()))

['Amazonía', 'Antioquia', 'Bogotá D.C.', 'Caribe', 'Cartagena', 'Central', 'Eje Cafetero', 'Golfo Morrosquillo y Sabana', 'Llanos Orinoquía', 'Pacífico', 'San Andrés y Providencia', 'Santanderes']


['Amazonía', 'Antioquia', 'Bogotá D.C.', 'Caribe', 'Cartagena', 'Central', 'Eje Cafetero', 'Golfo Morrosquillo y Sabana', 'Llanos Orinoquía', 'Pacífico', 'San Andrés y Providencia', 'Santanderes']

In [62]:
dataset_final = pd.merge(
    ocupacion_long,
    rnt_resumen,
    on="region",
    how="left",
    indicator=True
)

In [63]:
dataset_final["_merge"].value_counts()

_merge
both          1188
left_only        0
right_only       0
Name: count, dtype: int64

In [64]:
dataset_final.to_excel(
    "../data/dataset_cruzado.xlsx",
    index=False
)

print("Dataset guardado correctamente")

Dataset guardado correctamente

In [65]:
print(sorted(ocupacion_long["region"].unique()))

print(sorted(rnt_resumen["region"].unique()))

['Amazonía', 'Antioquia', 'Bogotá D.C.', 'Caribe', 'Cartagena', 'Central', 'Eje Cafetero', 'Golfo Morrosquillo y Sabana', 'Llanos Orinoquía', 'Pacífico', 'San Andrés y Providencia', 'Santanderes']
['Amazonía', 'Antioquia', 'Bogotá D.C.', 'Caribe', 'Cartagena', 'Central', 'Eje Cafetero', 'Golfo Morrosquillo y Sabana', 'Llanos Orinoquía', 'Pacífico', 'San Andrés y Providencia', 'Santanderes']

In [66]:
dataset_final["_merge"].value_counts()

_merge
both          1188
left_only        0
right_only       0
Name: count, dtype: int64

In [67]:
print(dataset_final.shape)

(1188, 7)

In [68]:
dataset_final.head()

,Año,Meses,region,ocupacion,establecimientos,habitaciones,_merge
0,2019,Enero,Bogotá D.C.,44.804505,49,49,both
1,2019,Febrero,Bogotá D.C.,58.725596,49,49,both
2,2019,Marzo,Bogotá D.C.,55.613889,49,49,both
3,2019,Abril,Bogotá D.C.,53.262452,49,49,both
4,2019,Mayo,Bogotá D.C.,58.275363,49,49,both

In [69]:
dataset_final["_merge"].value_counts()

_merge
both          1188
left_only        0
right_only       0
Name: count, dtype: int64